### PR TITLE
Fixes `Value.compare` (Closes #210)

### LINKED ISSUE #210: Fix `Value.compare`

### PR DESCRIPTION
**Pull request by filipeom**

### CODE REVIEW

File: src/value.ml [hunk 1]
```diff
@@ -28,23 +28,36 @@ let type_of (v : t) : Ty.t =
...
+  | List a, List b -> List.compare compare a b
   | App (`Op op1, vs1), App (`Op op2, vs2) ->
     let c = String.compare op1 op2 in
     if c = 0 then List.compare compare vs1 vs2 else c
   | ( ( True | False | Unit | Int _ | Real _ | Str _ | Num _ | List _ | App _
       | Nothing )
     , _ ) ->
-    assert false
+    (* TODO: I don't know if this is always semantically correct *)
+    Smtml_prelude.compare (discr a) (discr b)
```
Comment (zapashcanon) [inline src/value.ml:60]: maybe `Int.compare` instead?
